export default function Home () {
    return (
        <div className="home-wrapper main">
            <h1 className="shop-title">THE SHOPSHOP STOP</h1><h1 className="title under">Your ultimate shopping destination</h1>
            <p className="home-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae!</p>
            <h1 className="title under">Find what you need, when you need it</h1>
            <p className="home-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro.</p>
        </div>
    )
}