export default function Home () {
    return (
        <div className="home-wrapper main">
            <h1 className="title">Home Services Plumbing</h1>
            <p className="home-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae!</p>
            <h1 className="title">Schedule a consultation</h1>
            <p className="home-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error dolorem nemo ut iste quaerat natus molestias magnam incidunt distinctio obcaecati asperiores aspernatur, sequi similique fuga praesentium, placeat porro? Quos, molestiae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur veniam unde beatae non sed dignissimos, accusamus modi eaque qui, cupiditate numquam repellendus aspernatur amet ullam. Quaerat modi aspernatur ipsam porro.</p>
        </div>
    )
}